// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CF6F_yWLPaW7crCQImTq-FOc1kSIwAw',
    appId: '1:414775154733:web:4accb092cff40deac6c0a4',
    messagingSenderId: '414775154733',
    projectId: 'forbed-91065',
    authDomain: 'forbed-91065.firebaseapp.com',
    storageBucket: 'forbed-91065.appspot.com',
    measurementId: 'G-48QYX1ZMPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWnoceGyRaRszjr7UoZ8GXlPF9UvahBBQ',
    appId: '1:414775154733:android:f1e0b0218cc6183dc6c0a4',
    messagingSenderId: '414775154733',
    projectId: 'forbed-91065',
    storageBucket: 'forbed-91065.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ftTxDw2JpqZ9B4tbsnfLkhDJ2RZRVGw',
    appId: '1:414775154733:ios:dd52e50cae61951bc6c0a4',
    messagingSenderId: '414775154733',
    projectId: 'forbed-91065',
    storageBucket: 'forbed-91065.appspot.com',
    iosClientId: '414775154733-j2rhjt0vlee9unrkq8mds0l21svh8993.apps.googleusercontent.com',
    iosBundleId: 'com.example.forbeddashboard',
  );
}
